#macro STR_GAME_OVER  "GAME OVER"
#macro STR_HOLD  "HOLD / SWAP"
#macro STR_NEXT  "NEXT"
#macro STR_TITLE  "DICE ROYAL"
#macro STR_SCORE  "SCORE"
#macro STR_HUD_HIGH_SCORE  "HIGH SCORE"
#macro STR_LEVEL  "LEVEL"
#macro STR_CHAINS  "CHAINS"
#macro STR_LAST    "LAST"
#macro STR_BEST    "BEST"
#macro STR_UNLOCKS  "UNLOCKS"
#macro STR_UNLOCKS_NEXT_PREFIX  "NEXT: "
#macro STR_UNLOCKS_LEVEL_PREFIX " - LV"
#macro STR_UNLOCKS_ALL_DONE     "ALL UNLOCKED"
#macro STR_DIE_NAME_RANDOM   "RANDOMS"
#macro STR_DIE_NAME_CLEAR    "CLEAR LINES"
#macro STR_DIE_NAME_BOMB     "BOMBS"
#macro STR_DIE_NAME_JUNK     "JUNK DROPS"
#macro STR_DIE_NAME_BRICK    "LOCKS"
#macro STR_DIE_NAME_MIMIC    "MIMICS"
#macro STR_PAUSED        "PAUSED"
#macro STR_MENU_RESUME   "Resume"
#macro STR_MENU_RESTART  "Restart"
#macro STR_MENU_HELP     "Help"
#macro STR_MENU_QUIT     "Quit"
// Checkbox pieces for a toggle row. Assembled at draw time (scr_pause_item_text) rather than
// baked into one string per on/off state — the draw code colors each piece separately, and it
// used to re-parse a hardcoded "[X] " prefix back out of the finished string to do it.
#macro STR_TOGGLE_OPEN    "["
#macro STR_TOGGLE_CLOSE   "] "
#macro STR_TOGGLE_ON      "X"
#macro STR_TOGGLE_OFF     " "
#macro STR_MENU_MUTE_MUSIC  "Mute Music"
#macro STR_MENU_MUTE_SFX    "Mute SFX"
#macro STR_MENU_SHOW_GRID   "Show Grid"
#macro STR_MENU_SHOW_QUEUE  "Show Queue"
#macro STR_MENU_HOLD_SWAP   "Enable Hold / Swap"
#macro STR_MENU_GHOST       "Enable Preview"
#macro STR_VERSION    "Alpha Demo Version"
#macro STR_HELP_TITLE  "HOW TO PLAY"
#macro STR_HELP_RULES_1  "CONNECT DICE OF THE SAME VALUE"
#macro STR_HELP_RULES_2  "TO ELIMINATE THEM"
#macro STR_HELP_RULES_3  "2X2 - 3X3 - 4X4 - ETC"
#macro STR_HELP_RULES_4  "1'S ARE WILD"
#macro STR_HELP_RULES_5  "CONNECT IT TO ANY CHAIN"
#macro STR_HELP_RULES_6  "CLEAR ALL 1'S ON THE GRID"
#macro STR_HELP_CONTROLS_TITLE  "CONTROLS"
// Sits between the key and the action on a control row, drawn in its own color
#macro STR_HELP_CTRL_SEPARATOR  " = "
#macro STR_HELP_CTRL_KEY_1     "DRAG"
#macro STR_HELP_CTRL_ACTION_1  "MOVE LEFT / RIGHT"
#macro STR_HELP_CTRL_KEY_2     "SWIPE DOWN / UP"
#macro STR_HELP_CTRL_ACTION_2  "SOFT / HARD DROP"
#macro STR_HELP_CTRL_KEY_3     "TAP LEFT / RIGHT"
#macro STR_HELP_CTRL_ACTION_3  "ROTATE CCW / CW"
#macro STR_HELP_CTRL_KEY_4     "TAP BOTTOM"
#macro STR_HELP_CTRL_ACTION_4  "HOLD / SWAP"
#macro STR_HELP_BACK  "Back"
#macro STR_COUNTDOWN_GO    "STACK!"
#macro STR_NEW_BEST        "NEW BEST!"
#macro STR_CURRENT_SCORE   "Current Score"
#macro STR_HIGH_SCORE      "High Score"
#macro STR_TAP_TO_STACK    "Tap to STACK !!"
#macro STR_CREDITS         "CREDITS\nSim Graveline"
#macro STR_LOGO_MADE_WITH  "proudly made with"
#macro STR_LOGO_STUDIO     "GRAVE GAMES"
#macro STR_LOGO_PRESENTS   "PRESENTS"
#macro STATE_LOGOS    "logos"
#macro STATE_SPLASH   "splash"
#macro STATE_GAME     "game"
#macro FADE_OUT       "out"
#macro FADE_IN        "in"
#macro STR_INI_FILENAME    "diceroyal.ini"
#macro STR_INI_SECTION     "save"
#macro STR_INI_KEY_SCORE   "high_score"
#macro STR_INI_KEY_NAME    "high_score_name"
#macro STR_INI_KEY_MUSIC_MUTED    "music_muted"
#macro STR_INI_KEY_SFX_MUTED      "sfx_muted"
#macro STR_INI_KEY_GRID_LINES     "grid_lines"
#macro STR_INI_KEY_SHOW_QUEUE     "show_queue"
#macro STR_INI_KEY_HOLD_SWAP      "hold_swap_enabled"
#macro STR_INI_KEY_GHOST_ENABLED  "ghost_enabled"
#macro STR_INI_KEY_RUMBLE         "rumble_enabled"

// --- Touch HUD buttons ---
#macro STR_PAUSE  "||"
#macro STR_HELP       "?"
#macro STR_HELP_CLOSE "X"

#macro STR_MENU_RUMBLE  "Vibration"
