#macro STR_GAME_OVER  "GAME OVER"
#macro STR_HOLD  "HOLD"
#macro STR_NEXT  "NEXT"
#macro STR_TITLE  "DICE ROYAL"
#macro STR_SCORE  "SCORE"
#macro STR_LEVEL  "LEVEL"
#macro STR_PAUSE  "||"
#macro STR_PAUSED        "PAUSED"
#macro STR_MENU_RESUME   "Resume"
#macro STR_MENU_RESTART  "Restart"
#macro STR_MENU_QUIT     "Quit"
#macro STR_MENU_MUTE_ON   "[X] Mute Music"
#macro STR_MENU_MUTE_OFF  "[ ] Mute Music"
#macro STR_MENU_SFX_ON    "[X] Mute SFX"
#macro STR_MENU_SFX_OFF   "[ ] Mute SFX"
#macro STR_MENU_GHOST_ON   "[X] Ghost"
#macro STR_MENU_GHOST_OFF  "[ ] Ghost"
#macro STR_BETA_VERSION    "Beta Version"
#macro STR_HELP       "?"
#macro STR_HELP_CLOSE "X"
#macro STR_HELP_TITLE  "HOW TO PLAY"
#macro STR_HELP_RULES  "Connect dice of the same value\nto eliminate them:\n2x2  3x3  4x4  etc\n\n1's are wild - connect it to\nany dying die to clear all 1's"
#macro STR_HELP_CONTROLS  "Drag Left/Right to Move\nTap to Rotate\n\nSwipe Up to Hard Drop\nSwipe Down to Soft Drop\n\nTap Bottom to Hold a Pair"
#macro STR_COUNTDOWN_GO    "STACK!"
#macro STR_NEW_BEST        "NEW BEST!"
#macro STR_CURRENT_SCORE   "Current Score"
#macro STR_HIGH_SCORE      "High Score"
#macro STR_TAP_TO_STACK    "Tap to Stack!"
#macro STR_CREDITS         "CREDITS\nSim Graveline"
#macro STR_LOGO_MADE_WITH  "proudly made with"
#macro STR_LOGO_STUDIO     "GRAVE GAMES"
#macro STR_LOGO_PRESENTS   "PRESENTS"
#macro STATE_LOGOS    "logos"
#macro STATE_SPLASH   "splash"
#macro STATE_GAME     "game"
#macro FADE_OUT       "out"
#macro FADE_IN        "in"
#macro STR_INI_FILENAME    "diceroyal.ini"
#macro STR_INI_SECTION     "save"
#macro STR_INI_KEY_SCORE   "high_score"
#macro STR_INI_KEY_NAME    "high_score_name"