#macro STR_GAME_OVER  "GAME OVER"
#macro STR_HOLD  "HOLD / SWAP"
#macro STR_NEXT  "NEXT"
#macro STR_TITLE  "DICE ROYAL"
#macro STR_SCORE  "SCORE"
#macro STR_HUD_HIGH_SCORE  "HIGH SCORE"
#macro STR_LEVEL  "LEVEL"
#macro STR_CHAINS  "CHAINS"
#macro STR_LAST    "LAST"
#macro STR_BEST    "BEST"
#macro STR_UNLOCKS  "UNLOCKS"
#macro STR_UNLOCKS_NEXT_PREFIX  "NEXT: "
#macro STR_UNLOCKS_ALL_DONE     "ALL UNLOCKED"
#macro STR_DIE_NAME_RANDOM   "RANDOMS"
#macro STR_DIE_NAME_CLEAR    "CLEAR LINES"
#macro STR_DIE_NAME_BOMB     "BOMBS"
#macro STR_DIE_NAME_JUNK     "JUNK DROPS"
#macro STR_DIE_NAME_BRICK    "LOCKS"
#macro STR_DIE_NAME_MIMIC    "MIMICS"
#macro STR_PAUSED        "PAUSED"
#macro STR_MENU_RESUME   "Resume"
#macro STR_MENU_RESTART  "Restart"
#macro STR_MENU_HELP     "Help"
#macro STR_MENU_QUIT     "Quit"
#macro STR_MENU_MUTE_ON   "[X] Mute Music"
#macro STR_MENU_MUTE_OFF  "[ ] Mute Music"
#macro STR_MENU_SFX_ON    "[X] Mute SFX"
#macro STR_MENU_SFX_OFF   "[ ] Mute SFX"
#macro STR_MENU_SHOW_GRID_ON   "[X] Show Grid"
#macro STR_MENU_SHOW_GRID_OFF  "[ ] Show Grid"
#macro STR_MENU_SHOW_QUEUE_ON   "[X] Show Queue"
#macro STR_MENU_SHOW_QUEUE_OFF  "[ ] Show Queue"
#macro STR_MENU_HOLD_SWAP_ON   "[X] Enable Hold / Swap"
#macro STR_MENU_HOLD_SWAP_OFF  "[ ] Enable Hold / Swap"
#macro STR_MENU_GHOST_ON   "[X] Enable Preview"
#macro STR_MENU_GHOST_OFF  "[ ] Enable Preview"
#macro STR_BETA_VERSION    "Beta Version"
#macro STR_HELP_TITLE  "HOW TO PLAY"
#macro STR_HELP_RULES_1  "CONNECT DICE OF THE SAME VALUE"
#macro STR_HELP_RULES_2  "TO ELIMINATE THEM"
#macro STR_HELP_RULES_3  "2X2 - 3X3 - 4X4 - ETC"
#macro STR_HELP_RULES_4  "1'S ARE WILD"
#macro STR_HELP_RULES_5  "CONNECT IT TO ANY CHAIN"
#macro STR_HELP_RULES_6  "CLEAR ALL 1'S ON THE GRID"
#macro STR_HELP_CONTROLS_TITLE  "CONTROLS"
#macro STR_HELP_CTRL_KEY_1     "LEFT / RIGHT"
#macro STR_HELP_CTRL_ACTION_1  "MOVE LEFT / RIGHT"
#macro STR_HELP_CTRL_KEY_2     "DOWN / UP"
#macro STR_HELP_CTRL_ACTION_2  "SOFT / HARD DROP"
#macro STR_HELP_CTRL_KEY_3     "SPACEBAR / CTRL"
#macro STR_HELP_CTRL_ACTION_3  "ROTATE CW/CCW"
#macro STR_HELP_CTRL_KEY_4     "SHIFT"
#macro STR_HELP_CTRL_ACTION_4  "HOLD / SWAP"
#macro STR_HELP_CTRL_KEY_5     "TAB"
#macro STR_HELP_CTRL_ACTION_5  "TOGGLE GRID"
#macro STR_HELP_BACK  "Back"
#macro STR_COUNTDOWN_GO    "STACK!"
#macro STR_NEW_BEST        "NEW BEST!"
#macro STR_CURRENT_SCORE   "Current Score"
#macro STR_HIGH_SCORE      "High Score"
#macro STR_TAP_TO_STACK    "Press Any Key / Buttons"
#macro STR_CREDITS         "CREDITS\nSim Graveline"
#macro STR_LOGO_MADE_WITH  "proudly made with"
#macro STR_LOGO_STUDIO     "GRAVE GAMES"
#macro STR_LOGO_PRESENTS   "PRESENTS"
#macro STATE_LOGOS    "logos"
#macro STATE_SPLASH   "splash"
#macro STATE_GAME     "game"
#macro FADE_OUT       "out"
#macro FADE_IN        "in"
#macro STR_INI_FILENAME    "diceroyal.ini"
#macro STR_INI_SECTION     "save"
#macro STR_INI_KEY_SCORE   "high_score"
#macro STR_INI_KEY_NAME    "high_score_name"
#macro STR_INI_KEY_MUSIC_MUTED    "music_muted"
#macro STR_INI_KEY_SFX_MUTED      "sfx_muted"
#macro STR_INI_KEY_GRID_LINES     "grid_lines"
#macro STR_INI_KEY_SHOW_QUEUE     "show_queue"
#macro STR_INI_KEY_HOLD_SWAP      "hold_swap_enabled"
#macro STR_INI_KEY_GHOST_ENABLED  "ghost_enabled"